fragment CliDreamSummaryFields on Dream {
  id
  dreamDate
  status
  title
  imageUrl
  photoCount
  createdAt
}

fragment CliDreamFields on Dream {
  id
  dreamDate
  status
  title
  imageUrl
  photoCount
  createdAt
  userId
  errorMessage
  skipReason
  retryCount
  descriptionMarkdown
  imageWidth
  imageHeight
  imageBlurhash
  places
  cameraModels
  cameras {
    id
    make
    model
    imageCount
    sensorWidth
    sensorHeight
    shutterCount
    product {
      productImageUrl
      yearReleased
    }
  }
  placeClusters {
    id
    latitude
    longitude
    label
    imageCount
  }
}

fragment CliDreamImageFields on Image {
  id
  filename
  url
  thumbnailUrl
  status
  width
  height
  blurhash
  capturedAt
  latitude
  longitude
  cameraMake
  cameraModel
  rotation
  rate
  editedImages {
    url
    thumbnailUrl
    width
    height
    blurhash
    createdAt
  }
}

query CliDreams($pagination: InputPagination!) {
  dreams(pagination: $pagination) {
    edges {
      ...CliDreamSummaryFields
    }
    pageInfo {
      page
      pageSize
      totalCount
      totalPages
      hasNextPage
      hasPreviousPage
    }
  }
}

query CliDream($id: Int!, $pagination: InputPagination!) {
  dream(id: $id) {
    ...CliDreamFields
    images(pagination: $pagination, orderBy: RATE_DESC) {
      edges {
        ...CliDreamImageFields
      }
      pageInfo {
        page
        pageSize
        totalCount
        totalPages
        hasNextPage
        hasPreviousPage
      }
    }
  }
}

mutation CliRetryDream($id: Int!) {
  retryDream(id: $id) {
    id
    status
  }
}
