query Photos($filter: ImageFilter, $pagination: InputPagination!) {
  images(filter: $filter, pagination: $pagination) {
    edges {
      id
      filename
      url
      thumbnailUrl
      status
      width
      height
      capturedAt
      cameraMake
      cameraModel
      rotation
      rate
      editedImages {
        url
        thumbnailUrl
        width
        height
        blurhash
        createdAt
      }
    }
    pageInfo {
      page
      pageSize
      totalCount
      totalPages
      hasNextPage
      hasPreviousPage
    }
  }
}
