query SftpCredentials {
  sftpCredentials {
    id
    name
    lastUsedAt
    enabled
    createdAt
  }
}

mutation CreateSftpCredential($name: String!, $password: String) {
  createSFTPCredential(name: $name, password: $password) {
    id
    name
    password
    createdAt
  }
}

mutation DeleteSftpCredential($id: Int!) {
  deleteSFTPCredential(id: $id)
}
