query SftpCredentials {
  sftpCredentials {
    id
    name
    lastUsedAt
    enabled
    createdAt
  }
}

mutation CreateSftpCredential($name: String!) {
  createSFTPCredential(name: $name) {
    id
    name
    password
    createdAt
  }
}

mutation DeleteSftpCredential($id: Int!) {
  deleteSFTPCredential(id: $id)
}
