query UploadPreflight {
  me {
    id
    slug
    storageUsedBytes
    storageQuotaBytes
  }
  sftpCredentials {
    id
    enabled
  }
}

query ExistingUploadImages($filenames: [String!]!) {
  imagesByFilenames(filenames: $filenames) {
    id
    originalFilename
  }
}
